---
- name: Run remote profiler
  hosts: profiler
  tags: 
  - run_profiler
  tasks:
  - name: Run remote profiler
    command: "sudo python3 {{ PROFILER_HOME }}/profiler.py"
    async: 10000 
    poll: 0
    register: run_profiler_result_async
  - name: Check remote profiler
    async_status: jid="{{ run_profiler_result_async.ansible_job_id }}"
- name: Kill remote profiler
  hosts: profiler
  tags: 
  - kill_profiler
  tasks:
  - name: Get the PID of running process
    ignore_errors: yes
    shell: "ps -few | grep profiler | awk '{print $2}'"
    register: running_processes
  - name: Kill remote profiler       
    ignore_errors: yes
    shell: kill {{ item }}
    with_items: "{{ running_processes.stdout_lines }}"
